apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-21yt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-21yt
    app.kubernetes.io/part-of: test-app-858
  name: fbc-sample-repo-21yt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-21yt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-21yt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-858/fbc-sample-repo-21yt@sha256:5db444095f991b1948cb3a6d8d70e8c110de6acdf9a97c4400d5f4a45abc4ad4
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
