apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-o0sm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-o0sm
    app.kubernetes.io/part-of: test-app-858
  name: devfile-sample-python-basic-o0sm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-o0sm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-o0sm
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-858/devfile-sample-python-basic-o0sm@sha256:cbe5c286bb3fb8bf3676087e442bbe10156a3786966afeea3a04f597352f49a8
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
