apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-f5n2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-both-tag-digest-f5n2
    app.kubernetes.io/part-of: test-app-858
  name: e2e-tests-parent-image-with-both-tag-digest-f5n2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-f5n2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-f5n2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-858/e2e-tests-parent-image-with-both-tag-digest-f5n2@sha256:9bb08b26a9b522c48b2c078fca8c7e8fae99b61d7bd42e1c3999859308051942
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
